### ISSUE TITLE
How do you include an image in the chat message?

### ISSUE THREAD

**Issue by ianceicys** [esplorio/slack-countdown#6]
In the readme there is a photo of a countdown message that includes an image. How can I include an image in my countdown message?

**Comment by Denvar94** [comment]
In the countdown.py file, there is a method called post which sends a post request to your slack url. If you add this `"image-url":"your-url"` to the payload dictionary this will post a image with your message. https://api.slack.com/docs/attachments this link shows you other stuff you can add.

**Comment by ianceicys** [comment]
Interesting. I've added the "image-url":"your-url" but it's not showing up. 

http://i.imgur.com/U3ddio5.png

What am I missing?
